[build]
  command = "npm run build"
  publish = ".next"  # Corregido para apuntar a la carpeta .next

[context.production.environment]
  NODE_VERSION = "14"
  NEXT_TELEMETRY_DISABLED = "1"  # Desactiva la telemetría de Next.js en producción

[context.split1]
  command = "npm run split1-build"
  publish = "split1-build"

[context.split2]
  command = "npm run split2-build"
  publish = "split2-build"
